version: '3.9'
services:
  zoo1:
    image: url-shortener-zookeeper
    build:
      context: ./url_generator_service
      dockerfile: Dockerfile
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
